//
//  Exercise.swift
//  GymVisual crawler
//
//  Created by 정준영 on 2023/09/22.
//

import Foundation

enum BodyPart: String, CaseIterable {
    case chest = "Chest"
    case back = "Back"
    case shoulders = "Shoulders"
    case upperArms = "Upper Arms"
    case forearms = "Forearms"
    case waist = "Waist"
    case hips = "Hips"
    case thighs = "Thighs"
    case calves = "Calves"
    case neck = "Neck"
    case weightlifting = "Weightlifting"
    case plyometrics = "Plyometrics"
    case cardio = "Cardio"
}

enum EquipmentType: String, CaseIterable {
    case Barbell = "Barbell"
    case Dumbbell = "Dumbbell"
    case SmithMachine = "Smith machine"
    case Kettlebell = "Kettlebell"
    case BodyWeight = "Body weight"
    case Machine = "Machine"
    case Weighted = "Weighted"
    case Cable = "Cable"
}

enum TargetMuscles: String {
    case AdductorLongus = "Adductor Longus"
    case Iliopsoas = "Iliopsoas"
    case Splenius = "Splenius"
    case TeresMinor = "Teres Minor"
    case TeresMajor = "Teres Major"
    case PectoralisMajorSternalHead = "Pectoralis Major Sternal Head"
    case AdductorMagnus = "Adductor Magnus"
    case ErectorSpinae = "Erector Spinae"
    case Gastrocnemius = "Gastrocnemius"
    case TibialisAnterior = "Tibialis Anterior"
    case DeltoidLateral = "Deltoid Lateral"
    case RectusAbdominis = "Rectus Abdominis"
    case SerratusAnterior = "Serratus Anterior"
    case AdductorBrevis = "Adductor Brevis"
    case Subscapularis = "Subscapularis"
    case PectoralisMajorClavicularHead = "Pectoralis Major Clavicular Head"
    case DeltoidAnterior = "Deltoid Anterior"
    case GluteusMinimus = "Gluteus Minimus"
    case Obliques = "Obliques"
    case WristExtensors = "Wrist Extensors"
    case Infraspinatus = "Infraspinatus"
    case DeltoidPosterior = "Deltoid Posterior"
    case LevatorScapulae = "Levator Scapulae"
    case TransverseAbdominus = "Transverse Abdominus"
    case GluteusMedius = "Gluteus Medius"
    case Quadriceps = "Quadriceps"
    case TricepsBrachii = "Triceps Brachii"
    case TrapeziusLowerFibers = "Trapezius Lower Fibers"
    case Brachialis = "Brachialis"
    case Soleus = "Soleus"
    case TensorFasciaeLatae = "Tensor Fasciae Latae"
    case Brachioradialis = "Brachioradialis"
    case Hamstrings = "Hamstrings"
    case WristFlexors = "Wrist Flexors"
    case TrapeziusMiddleFibers = "Trapezius Middle Fibers"
    case TrapeziusUpperFibers = "Trapezius Upper Fibers"
    case Gracilis = "Gracilis"
    case Sternocleidomastoid = "Sternocleidomastoid"
    case LatissimusDorsi = "Latissimus Dorsi"
    case GluteusMaximus = "Gluteus Maximus"
    case BicepsBrachii = "Biceps Brachii"
    case Pectineous = "Pectineous"
}


enum SynergistMuscles: String {
    case TibialisAnterior = "Tibialis Anterior"
    case PectoralisMajorSternalHead = "Pectoralis Major Sternal Head"
    case Iliopsoas = "Iliopsoas"
    case LevatorScapulae = "Levator Scapulae"
    case GluteusMedius = "Gluteus Medius"
    case DeltoidAnterior = "Deltoid Anterior"
    case AdductorBrevis = "Adductor Brevis"
    case TrapeziusUpperFibers = "Trapezius Upper Fibers"
    case TensorFasciaeLatae = "Tensor Fasciae Latae"
    case Subscapularis = "Subscapularis"
    case PectoralisMajorClavicularHead = "Pectoralis Major Clavicular Head"
    case Obliques = "Obliques"
    case Infraspinatus = "Infraspinatus"
    case WristExtensors = "Wrist Extensors"
    case GluteusMaximus = "Gluteus Maximus"
    case BicepsBrachii = "Biceps Brachii"
    case Brachioradialis = "Brachioradialis"
    case TrapeziusMiddleFibers = "Trapezius Middle Fibers"
    case AdductorMagnus = "Adductor Magnus"
    case Splenius = "Splenius"
    case DeltoidPosterior = "Deltoid Posterior"
    case RectusAbdominis = "Rectus Abdominis"
    case TrapeziusLowerFibers = "Trapezius Lower Fibers"
    case Sartorius = "Sartorius"
    case Hamstrings = "Hamstrings"
    case Brachialis = "Brachialis"
    case Quadriceps = "Quadriceps"
    case TricepsBrachii = "Triceps Brachii"
    case SerratusAnterior = "Serratus Anterior"
    case DeltoidLateral = "Deltoid Lateral"
    case WristFlexors = "Wrist Flexors"
    case Gracilis = "Gracilis"
    case Sternocleidomastoid = "Sternocleidomastoid"
    case LatissimusDorsi = "Latissimus Dorsi"
    case Popliteus = "Popliteus"
    case AdductorLongus = "Adductor Longus"
    case Gastrocnemius = "Gastrocnemius"
    case TeresMinor = "Teres Minor"
    case TeresMajor = "Teres Major"
    case Pectineous = "Pectineous"
    case ErectorSpinae = "Erector Spinae"
    case Soleus = "Soleus"
}

